version: '3'
services:
  client:
    build:
      context: ./Client
    container_name: node-react
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./Backend
    container_name: node-api
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: mongo-db
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
