version: '3'
services:
  client:
    build:
      context: ./Client
    container_name: node-react
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build:
      context: ./Backend
    container_name: node-api
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - mern-network

  mongodb:
    image: mongo
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: Thoshinny
      MONGO_INITDB_ROOT_PASSWORD: Hamyeong*4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
volumes:
  mongo-data:
